### ISSUE TITLE
Missing question mark for 'this' in 'perf test' command

### ISSUE THREAD

**Issue by rbuckton** [weswigham/typescript-bot-test-triggerer#4]
https://github.com/weswigham/typescript-bot-test-triggerer/blob/35b859b8945bcdf9a34d7ed45ffeaa03fd40c4e3/GithubCommentReader/index.js#L226-L227

I think this is supposed to be `/perf test(?: this)?(?! faster)` (so that ` this` is optional)

**Comment by weswigham** [comment]
Good catch - I've added 'em: https://github.com/weswigham/typescript-bot-test-triggerer/commit/f6c96a85834a21af1a9bf8fa8b3428992aff5090 Change should be live as soon as the deploy is done.
